// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAPzfBd8Vr7ShCt-EJrgtQ6-jEJ9Hc_PQ',
    appId: '1:499165897164:android:5a6197215c7b7ccedbfd69',
    messagingSenderId: '499165897164',
    projectId: 'doctor-appointment-9cd85',
    storageBucket: 'doctor-appointment-9cd85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbiyAojYyQxmh-Qc740-mWkiftvlzZgoQ',
    appId: '1:499165897164:ios:4c7c933fea5c8d65dbfd69',
    messagingSenderId: '499165897164',
    projectId: 'doctor-appointment-9cd85',
    storageBucket: 'doctor-appointment-9cd85.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbiyAojYyQxmh-Qc740-mWkiftvlzZgoQ',
    appId: '1:499165897164:ios:4c7c933fea5c8d65dbfd69',
    messagingSenderId: '499165897164',
    projectId: 'doctor-appointment-9cd85',
    storageBucket: 'doctor-appointment-9cd85.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointment',
  );

}